#!/usr/bin/env bash
#clock function that displays time for 12h59m
i=0
h=0
echo "Hour: $h";
while [ $h -lt 12 ]
do
    i=$((i + 1));
    case "$i" in
	"0") echo "Hour: $h"; echo "$i";;
	"59") echo "$i"; i=0; h=$((h + 1)); echo "Hour: $h";;
        *) echo "$i";;
    esac
done
