#!/usr/bin/env bash
#clock function that displays time for 12h59m
i=1
h=0
echo "Hour: $h";
while [ $h -le 12 ]
do
    if [ $h -lt 12 ]
       then
    while [ $i -le 59 ]
    do
	echo "$i"; i=$((i + 1))
    done
    h=$((h + 1)); echo "Hour: $h"; i=1;
    else
        h=$((h + 1)); i=1;
	fi
done
	while [ $i -le 59 ]
	do
	      echo "$i"; i=$((i + 1));
	done


